### PR TITLE
Adding System.Runetime.CompilerServices.Unsafe.dll

### PR DESCRIPTION
**Pull request by chunloklo**
Adding System.Runetime.CompilerServices.Unsafe.dll
Otherwise Unity will not be able to find the dll.

### CODE REVIEW

**Comment by james7132** [comment]
What version of Unity are you testing this with? Unity had included it with their 2019.x packages at some point, which is why it wasn't included. I will not object to removing support for Unity versions before 2019.4, but we need to note it on the associated documentation and READMEs.

**Comment by chunloklo** [comment]
> What version of Unity are you testing this with? Unity had included it with their 2019.x packages at some point, which is why it wasn't included. I will not object to removing support for Unity versions before 2019.4, but we need to note it on the associated documentation and READMEs.

I'm testing this with Unity 2019.4.16f1. I know it's "supposed" to be included, and I did find it within the C# files, but it somehow just wasn't recognizing it for some reason :\ I've tried installing it other ways too but this is the fix that worked for me.

**Comment by goodiesohhi** [comment]
Yeah. I can confer. The dll exists in the package cache for burst but for whatever reason, I can't get it to work.

**Comment by james7132** [comment]
The same issue is documented here on the Unity forums: https://forum.unity.com/threads/please-update-com-unity-collections-reference-of-system-runtime-compilerservices-unsafe.732056/

In the same thread, it says that this conflict is likely not going to be resolved on 2019.4 LTS in any capacity. This likely will mean we need to bump the minimum supported Unity version to 2020.1. 

I can approve this now as a short term fix, but I'm concerned about other potential conflicts as System.CompilerServices.Unsafe/System.Buffers/System.Memory is a very commonly used DLL across the C# ecosystem. Conflicts are inevitably going to show up.

**Pull request merged**
